const productMode = document.getElementById("productMode");
const existingProductWrap = document.getElementById("existingProductWrap");
const existingProduct = document.getElementById("existingProduct");

const taskTypeContainer = document.getElementById("taskType");
const hypothesisSection = document.getElementById("hypothesisSection");
const synthesisSection = document.getElementById("synthesisSection");
const hypothesisInput = document.getElementById("hypothesisInput");

const analyzeBtn = document.getElementById("analyzeBtn");
const emptyState = document.getElementById("emptyState");
const result = document.getElementById("result");

let taskType = "hypothesis";

productMode.addEventListener("change", () => {
  existingProductWrap.hidden = productMode.value !== "existing";
});

taskTypeContainer.addEventListener("click", (e) => {
  const btn = e.target.closest(".seg");
  if (!btn) return;

  [...taskTypeContainer.querySelectorAll(".seg")].forEach((b) => b.classList.remove("active"));
  btn.classList.add("active");
  taskType = btn.dataset.value;

  hypothesisSection.hidden = taskType !== "hypothesis";
  synthesisSection.hidden = taskType !== "synthesis";
});

analyzeBtn.addEventListener("click", () => {
  const chosenProduct =
    productMode.value === "existing" ? existingProduct.value : "New Product Initiative";

  if (taskType === "hypothesis") {
    const hypothesis = hypothesisInput.value.trim();
    if (!hypothesis) {
      alert("Please enter a hypothesis first.");
      return;
    }
    renderHypothesisResult(chosenProduct, hypothesis);
  } else {
    const selectedSources = [...document.querySelectorAll('#synthesisSection input[type="checkbox"]:checked')]
      .map((c) => c.value);

    if (!selectedSources.length) {
      alert("Please select at least one data source.");
      return;
    }
    renderSynthesisResult(chosenProduct, selectedSources);
  }
});

function renderHypothesisResult(product, hypothesis) {
  const score = simulatedConfidence(hypothesis);
  const validated = score >= 0.52;
  const decision = validated ? "Validated" : "Invalidated";

  const evidence = buildEvidenceForHypothesis(hypothesis);

  result.innerHTML = `
    <article class="result-card">
      <div class="kpis">
        <div class="kpi">Product: <strong>${escapeHtml(product)}</strong></div>
        <div class="kpi">Mode: <strong>Hypothesis Test</strong></div>
        <div class="kpi">AI Confidence: <strong>${Math.round(score * 100)}%</strong></div>
      </div>

      <div class="card">
        <h3>Hypothesis Decision <span class="status ${validated ? "validated" : "invalidated"}">${decision}</span></h3>
        <p><strong>Hypothesis:</strong> ${escapeHtml(hypothesis)}</p>
        <p>
          The current evidence ${validated ? "supports" : "does not sufficiently support"} this hypothesis.
          ${validated
            ? "Signals indicate measurable uplift aligned to strategic goals."
            : "Signals are mixed or weak against strategic impact and confidence thresholds."}
        </p>
      </div>

      <div class="card">
        <h3>Evidence Used</h3>
        <ul class="list">
          ${evidence.map((e) => `<li>${escapeHtml(e)}</li>`).join("")}
        </ul>
      </div>

      <div class="card">
        <h3>Strategic Recommendation</h3>
        <p>
          ${validated
            ? "Prioritize a scoped rollout with success metrics tied to activation, retention, and business impact."
            : "Do not prioritize broad implementation yet. Run a constrained experiment to collect stronger causal evidence."}
        </p>
        <p class="small">Generated by ProdPriority AI Oracle + CoPilot prototype.</p>
      </div>
    </article>
  `;
  showResult();
}

function renderSynthesisResult(product, sources) {
  const insights = buildSynthesisInsights(sources);

  result.innerHTML = `
    <article class="result-card">
      <div class="kpis">
        <div class="kpi">Product: <strong>${escapeHtml(product)}</strong></div>
        <div class="kpi">Mode: <strong>Synthesis</strong></div>
        <div class="kpi">Sources: <strong>${sources.length}</strong></div>
      </div>

      <div class="card">
        <h3>Synthesized Insights</h3>
        <ul class="list">
          ${insights
            .map(
              (i) => `
                <li>
                  <strong>${escapeHtml(i.title)}</strong>
                  <span class="priority ${i.priority.toLowerCase()}">${i.priorityLabel}</span><br />
                  ${escapeHtml(i.reasoning)}
                </li>`
            )
            .join("")}
        </ul>
      </div>

      <div class="card">
        <h3>Data Sources Used</h3>
        <ul class="list">
          ${sources.map((s) => `<li>${escapeHtml(s)}</li>`).join("")}
        </ul>
      </div>

      <div class="card">
        <h3>Strategic Alignment Summary</h3>
        <p>
          Prioritization is weighted against business strategy pillars: growth efficiency,
          retention impact, and delivery feasibility. Highest priority items represent the
          strongest combination of user pain, commercial upside, and execution readiness.
        </p>
        <p class="small">Generated by ProdPriority AI Oracle + CoPilot prototype.</p>
      </div>
    </article>
  `;
  showResult();
}

function simulatedConfidence(text) {
  // deterministic-ish prototype logic based on text composition
  const lenFactor = Math.min(text.length / 180, 1);
  const keywordBoost =
    /(increase|reduce|activation|retention|conversion|revenue|churn|engagement)/i.test(text) ? 0.14 : 0.02;
  const metricBoost = /\d+%|\d+\s?(days|weeks|months|points)/i.test(text) ? 0.12 : 0.01;
  return Math.min(0.35 + lenFactor * 0.35 + keywordBoost + metricBoost, 0.92);
}

function buildEvidenceForHypothesis(hypothesis) {
  const base = [
    "Product analytics trend segments (last 90 days) for activation and retention behavior.",
    "Support ticket taxonomy highlighting repeated friction points linked to the hypothesis area.",
    "NPS/comment sentiment clusters for affected user cohorts and journey stages.",
    "Roadmap + OKR alignment check against quarterly strategic objectives.",
  ];

  if (/onboard|activation/i.test(hypothesis)) {
    base.push("Onboarding funnel drop-off analysis by step and persona.");
  }
  if (/retention|churn/i.test(hypothesis)) {
    base.push("Cohort retention decay comparison across users exposed vs not exposed to the proposed change.");
  }
  if (/pricing|plan|billing|revenue/i.test(hypothesis)) {
    base.push("Plan conversion and expansion signals from billing and sales-assist notes.");
  }
  return base;
}

function buildSynthesisInsights(sources) {
  const catalog = [
    {
      title: "Onboarding friction for first-week users is driving early drop-off.",
      priority: "p1",
      priorityLabel: "P1 • High",
      reasoning: "Appears across behavior events, support issues, and qualitative feedback with direct activation impact.",
    },
    {
      title: "Power users request advanced workflow automation to reduce repetitive actions.",
      priority: "p2",
      priorityLabel: "P2 • Medium",
      reasoning: "Strong in interviews and sales notes, with moderate impact on expansion and retention.",
    },
    {
      title: "In-app guidance gaps create avoidable support load and slower time-to-value.",
      priority: "p1",
      priorityLabel: "P1 • High",
      reasoning: "Recurring issue with measurable operational cost and customer experience impact.",
    },
    {
      title: "Reporting customization is a differentiator but affects a narrower segment.",
      priority: "p3",
      priorityLabel: "P3 • Moderate",
      reasoning: "Important for enterprise personas but lower broad-user urgency than activation blockers.",
    },
  ];

  // bias results based on selected sources for a more dynamic feel
  const hasSupport = sources.includes("Support Tickets");
  const hasAnalytics = sources.includes("Product Analytics Events");
  const hasRoadmap = sources.includes("Roadmap & OKRs");

  let selected = [...catalog];
  if (!hasSupport) selected = selected.filter((i) => !i.title.includes("support load"));
  if (!hasAnalytics) selected = selected.filter((i) => !i.title.includes("drop-off"));
  if (!hasRoadmap) selected.push({
    title: "Potential strategy misalignment risk due to limited OKR linkage in source set.",
    priority: "p2",
    priorityLabel: "P2 • Medium",
    reasoning: "Insight confidence is reduced when strategic objective mapping is absent.",
  });

  return selected.slice(0, 4);
}

function showResult() {
  emptyState.hidden = true;
  result.hidden = false;
  result.scrollIntoView({ behavior: "smooth", block: "start" });
}

function escapeHtml(str) {
  return str
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#039;");
}
